name = "betterbili-pwa"
compatibility_date = "2024-04-01"
pages_build_output_dir = "dist"

[vars]
VITE_API_URL = "http://localhost:8080/api/v1"

[env.production.vars]
VITE_API_URL = "https://api.betterbili.com/api/v1"

[env.staging.vars]
VITE_API_URL = "https://staging-api.betterbili.com/api/v1"
